config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  
  resources :groups, path: '/categories' do
    resources :payments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_payments
  has_many :payments, through: :group_payments

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true
end

app/models/group_payment.rb
class GroupPayment < ApplicationRecord
  belongs_to :group
  belongs_to :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :group_payments
  has_many :groups, through: :group_payments
  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :payments, foreign_key: 'author_id'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |f|
      if @group.save
        f.html { redirect_to groups_path, notice: 'The Category was created successfully.' }
      else
        f.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_group, only: %i[index new create]

  def index
    @payments = @group.payments.order(created_at: :desc)
  end

  def new
    @payment = Payment.new
    @groups = current_user.groups
  end

  def create
    if params[:payment][:groups].blank?
      flash[:alert] = 'Must select at least one category'
      redirect_to new_group_payment_path(@group)
    else
      @payment = current_user.payments.build(payment_params)

      if @payment.save
        create_group_payments(params[:payment][:groups], @payment)
        redirect_to group_payments_path(@group), notice: 'The Payment was added successfully.'
      else
        render :index, status: :unprocessable_entity
      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, categories: [])
  end

  def create_group_payments(group_ids, payment)
    group_ids.each do |group_id|
      GroupPayment.create(group_id:, payment:)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<% content_for :navbar_title, 'Categories'.upcase %>

<section class="categories-section">
  <% unless @groups.present? %>
    <div class="empty-categories">
      <p>You have no categories yet, start by adding one using the button below</p>
    </div>
  <% end %>
  <% @groups.each do |group| %>
    <%= link_to group_payments_path(group.id), class: "category-box" do %>
      <article>
        <figure>
          <p>
            <img src=<%= group.icon %> class="category-icon">
          </p>
        </figure>
        <div>
          <div>
            <p>
              <strong><%= group.name %></strong>
            </p>
          </div>
          <hr class="category-separator">
          <div>
            <div>
              <small>Payments total:
                <%= number_to_currency(group.payments.sum(:amount)) %></small>
            </div>
          </div>
        </div>
      </article>
    <% end %>
  <% end %>
</section>
<div>
  <%= link_to "Add Category", new_group_path, class: "add-category-link" %>
</div>

app/views/groups/new.html.erb
<% provide(:title, "New Category".upcase) %>

<div class="new-category-form">
  <%= form_with model: @group, class: "category-form" do |form| %>
    <% if @group.errors.any? %>
      <div class="error-messages">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% @group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.text_field :name, placeholder: "Name", class: "input-field" %>
    </div>
    
    <div class="form-field">
      <%= form.url_field :icon, placeholder: "Icon (URL)", class: "input-field" %>
    </div>

    <div class="form-actions">
      <%= form.submit 'Create Category', class: "submit-button" %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<% content_for :navbar_title, 'My Expenses APP'.upcase %>

<div class="buttons">
<%= link_to "LOG IN", new_user_session_path, class:"button-login"%> <br>
<%= link_to "SIGN UP", new_user_registration_path, class:"button-login"%> <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetRor</title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'payments', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'categories', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>     
    <p class="alert"><%= alert %></p>
    <%= render '/shared/nav' %>

    <%= yield %> 
    
  </body>
</html>

app/views/payments/index.html.erb
<% content_for :navbar_title, 'Expenses'.upcase %>

<section class="payments-section">
  <div class="payments-total">
    <small>Payments total: <%= number_to_currency(@payments.sum(:amount)) %></small>
  </div>

  <% unless @payments.present? %>
    <div class="no-payments">
      <p>You have no payments yet, start by adding one using the button at the bottom</p>
    </div>
  <% end %>

  <% @payments.each do |payment| %>
    <div class="payment">
      <div class="payment-details">
        <div class="payment-name">
          <p><%= payment.name %></p>
        </div>
        <div class="payment-amount">
          <strong>Amount: <%= number_to_currency(payment.amount) %></strong>
        </div>
      </div>
      <hr>
      <div class="payment-created-at">
        <small>Created at: <%= payment.created_at.to_fs(:short) %></small>
      </div>
    </div>
  <% end %>
</section>

<div class="add-payment-button">
  <%= link_to "Add Payment", new_group_payment_path %>
</div>

app/views/payments/new.html.erb
<% provide(:title, "New Payment".upcase) %>
<% provide(:link, group_payments_path(params[:group_id])) %>

<div class="payment-form">
  <%= form_with(model: @payment, url: group_payments_path(params[:group_id])) do |form| %>
    <% if @payment.errors.any? %>
      <div class="payment-errors">
        <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

        <ul>
          <% @payment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.text_field :name,
                      class: "input",
                      required: true,
                      placeholder: "Name" %>
    </div>

    <div class="form-field">
      <%= form.number_field :amount,
                        step: :any,
                        required: true,
                        placeholder: "Amount ($)",
                        class: "input px-3" %>
    </div>

    <div class="form-field">
      <%= form.label "Choose Categories (at least one):", class: "label" %>
      <% @groups.each do |item| %>
        <div class="category-field">
          <%= check_box_tag "payment[groups][]",
          item.id,
          item.id == @group.id,
          class: "checkbox" %>
          <%= form.label item.name, class: "checkbox" %>
        </div>
      <% end %>
    </div>

    <div class="form-actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar">
  <div class="navbar-wrapper">
  <%= link_to raw('<p>Back: &#8592;</p>'), request.referrer, class: "nav-link" %>
    <%= yield(:navbar_title) %>
    <div class="navbarlinks">
      <ul class="navbar-ul">
      <% if current_user %>
      Welcome <%= link_to current_user.name, edit_user_registration_path, class: 'nav-link' %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "logout" %>
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
      </ul>
      <ul class="navbar-ul">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
          <span>-</span>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", groups_path, class: "nav-link" %>
          <span>-</span>
        </li>
      </ul>
    </div>
  </div>
</nav>